### ISSUE TITLE
Issue with the SVHN Dataset 

### ISSUE THREAD

**Issue by vruvora** [dribnet/kerosene#1]
@dribnet I am having an issue running the SVHN example. MNIST and CIFAR 10 work and download fine. However, SVHN keeps giving me an error. 

`from kerosene.datasets import svhn`
`svhn2.load_data()`

Here is the error I receive: 

```
h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)()

h5py/h5f.pyx in h5py.h5f.open (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1816)()

IOError: Unable to open file (Truncated file: eof = 24640512, sblock->base_addr = 0, stored_eoa = 1937295092)
```

**Comment by factom** [comment]
Awesome to hear that MNIST and CIFAR10 are working for you - I'll check on SVHN tonight. 

I think this has happened for me when there is an aborted or corrupt download, so one thing you can try in the meantime is clearing the local download cache:

```bash
rm -Rf ~/.kerosene/datasets
```

A little less extreme is to try removing just the SVHN hdf5, which I *think* is called `svhn_format_2<version>.hdf5` in that directory, so that other unrelated datasets don't have to be downloaded again. 

When the file is not found in the cache, it will trigger the download again. If this works for you, an improvement to the library would be to add checksums or some such so that this doesn't happen again.

**Comment by dribnet** [comment]
Awesome to hear that MNIST and CIFAR10 are working for you - I'll check on SVHN tonight.

I think this has happened for me when there is an aborted or corrupt download, so one thing you can try in the meantime is clearing the local download cache:

``` bash
rm -Rf ~/.kerosene/datasets
```

A little less extreme is to try removing just the SVHN hdf5, which I think is called `svhn_format_2-<version>.hdf5` in that directory, so that other unrelated datasets don't have to be downloaded again.

When the file is not found in the cache, it will trigger the download again. If this works for you, an improvement to the library would be to add checksums or some such so that this doesn't happen again.

**Comment by dribnet** [comment]
@vruvora - I can't reproduce the issue - I re-downloaded the file and ran `python examples/svhn2.py` in this repo without a hitch. If you have a local file called `~/.kerosene/datasets/svhn_format_2-0.1.0.hdf5` can you try deleting that and running again? Or if you are still having the issue let me know and we can try tracking it down.

**Comment by vruvora** [comment]
Got it thanks! Deleting the cache helped -- thanks for a prompt response!
